// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfioPB-4QORB8uyB9qRFAl-_q-q1cNhg',
    appId: '1:334331961632:web:9cd7dde08bef106d6af745',
    messagingSenderId: '334331961632',
    projectId: 'miniproject-29dc8',
    authDomain: 'miniproject-29dc8.firebaseapp.com',
    storageBucket: 'miniproject-29dc8.appspot.com',
    measurementId: 'G-X358QV5XL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVulna02zbjERQrrv25_1FZpgSSpy_l8',
    appId: '1:334331961632:android:0b98d9280d96000c6af745',
    messagingSenderId: '334331961632',
    projectId: 'miniproject-29dc8',
    storageBucket: 'miniproject-29dc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9j6at32qToIWJGJ399DJegdXMcgpKyQ',
    appId: '1:334331961632:ios:78851355a50568796af745',
    messagingSenderId: '334331961632',
    projectId: 'miniproject-29dc8',
    storageBucket: 'miniproject-29dc8.appspot.com',
    iosBundleId: 'com.example.dotslash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg9j6at32qToIWJGJ399DJegdXMcgpKyQ',
    appId: '1:334331961632:ios:0c20008ef52e90a36af745',
    messagingSenderId: '334331961632',
    projectId: 'miniproject-29dc8',
    storageBucket: 'miniproject-29dc8.appspot.com',
    iosBundleId: 'com.example.dotslash.RunnerTests',
  );
}
